### ISSUE TITLE
Сайт

### ISSUE THREAD

**Issue by puppets2666** [SvyatoslavFedynyak/MyReposytoriySF#15]
я зроблю, хто за?

**Comment by SvyatoslavFedynyak** [comment]
Чо там у проекта?

**Comment by Lenkelheit** [comment]
а що за проект?

**Comment by Lenkelheit** [comment]
![image](https://user-images.githubusercontent.com/38116562/39041512-9079a1e4-4491-11e8-8d11-f7b3a74604db.png)

**Comment by Lenkelheit** [comment]
ти закрив?

**Comment by puppets2666** [comment]
це не тут тре питати!

**Comment by puppets2666** [comment]
в іншій Issue

**Comment by puppets2666** [comment]
Я не можу робити сайт, це не мій репозиторій!
