### ISSUE TITLE
Коротко про мене в цій практичній

### ISSUE THREAD

**Issue by SvyatoslavFedynyak** [SvyatoslavFedynyak/MyReposytoriySF#16]
![image](https://user-images.githubusercontent.com/36925520/39041665-dada5012-4491-11e8-93b3-2b398499f31b.png)

**Comment by Lenkelheit** [comment]
Лайк однозначно!)

**Comment by Lenkelheit** [comment]
![image](https://user-images.githubusercontent.com/38116562/39041755-ff156caa-4491-11e8-8844-a87e4a06289b.png)

**Comment by puppets2666** [comment]
все гуд

**Comment by LausDio** [comment]
![image](https://user-images.githubusercontent.com/38051700/39041974-76c911ca-4492-11e8-8ab1-96827cb59abd.png)

**Comment by Lenkelheit** [comment]
![image](https://user-images.githubusercontent.com/38116562/39041978-7907ca8a-4492-11e8-81c1-85d044f0bfd0.png)
